version: '3'
services:
    # PHP Service (админка Spectrum)
    spectrum_php:
        container_name: spectrum_php
        build:
            context: .
            dockerfile: Dockerfile
        image: digitalocean.com/php
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./.env:/var/www/.env
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - shared-media-network
        extra_hosts:
            #get update ip: nslookup www.imdb.com or dig www.imdb.com
            - "m.media-amazon.com:212.188.39.27"
            - "www.imdb.com:3.174.109.174"
            - "api.themoviedb.org:13.225.89.239"
            - "image.tmdb.org:13.225.89.239"
            - "www.themoviedb.org:13.225.89.239"       # Веб-сайт
            - "api-v3.themoviedb.org:13.225.89.239"    # API v3
            - "assets.tmdb.org:13.225.89.239"          # Ассеты
            - "api.themoviedb.org:13.226.238.73"       # Альтернативный IP 1
            - "api.themoviedb.org:13.226.238.120"      # Альтернативный IP 2
            - "api.themoviedb.org:13.226.238.38"       # Альтернативный IP 3
    # Nginx Service (для админки)
    spectrum_webserver:
        container_name: spectrum_webserver
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - shared-media-network
    # MySQL Service
    spectrum_db:
        container_name: spectrum_db
        image: mysql:5.7.22
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - dbdata:/var/lib/mysql/
            - ./mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - shared-media-network
    # Redis Service
    spectrum_redis:
        container_name: spectrum_redis
        image: redis:latest
        ports:
            - "6379:6379"
        volumes:
            - ./redisdata:/data
        command: ["redis-server", "--bind", "spectrum_redis", "--port", "6379","--stop-writes-on-bgsave-error", "no"]
        networks:
            - shared-media-network
    # Adminer client
    spectrum_adminer:
        container_name: spectrum_adminer
        restart: unless-stopped
        image: adminer:4
        environment:
            ADMINER_DEFAULT_DB_DRIVER: mysql
            ADMINER_DEFAULT_DB_HOST: db:3306
            ADMINER_DEFAULT_DB_NAME: database_spectrum
        depends_on:
            - spectrum_db
        ports:
            - "${ADMINER_PORT:-8080}:8080"
        networks:
            - shared-media-network
    # Composer
    spectrum_composer:
        container_name: spectrum_composer
        image: composer:latest
        tty: true
        volumes:
            - ./:/var/www
        working_dir: /var/www
        depends_on:
            - spectrum_php
        networks:
            - shared-media-network
    # NPM
    spectrum_npm:
        container_name: spectrum_npm
        build:
            context: .
            dockerfile: Dockerfile.node
        tty: true
        ports:
            - "5173:5173"
        volumes:
            - ./:/var/www
        working_dir: /var/www
        command: ["npm", "run", "dev", "--", "--host"]
        networks:
            - shared-media-network
    # SOCKET
    spectrum_socket:
        container_name: spectrum_socket
        build:
            context: .
            dockerfile: Dockerfile.node
        tty: true
        volumes:
            - ./:/var/www
            - /var/www/node_modules
        working_dir: /var/www
        command: [ "node", "server.js" ]
        networks:
            - shared-media-network
        depends_on:
            - spectrum_redis
            - spectrum_db
    # QUEUE
    spectrum_queue_worker:
        container_name: spectrum_queue_worker
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./.env:/var/www/.env
        networks:
            - shared-media-network
        command: [ "php", "artisan", "queue:work", "--sleep=3", "--tries=3" ]
        restart: unless-stopped
        depends_on:
            - spectrum_redis
            - spectrum_db
networks:
    shared-media-network:
        external: true
volumes:
    dbdata:
        driver: local
